### ISSUE TITLE
Errors building on OS X

### ISSUE THREAD

**Issue by orcutt989** [NetLogo/Gradient-Extension#1]
I unzipped the files into /Applications/NetLogo 5.2 and then ran make from that directory after deleting gradient.jar to compile my own... I got the following errors.

macjimmy:NetLogo 5.2 $ make
mkdir -p classes
/usr/bin/javac -g -deprecation -Xlint:all -Xlint:-serial -Xlint:-path -encoding us-ascii -source 1.5 -target 1.5 -classpath ../../NetLogoLite.jar -d classes src/ColorGradient.java src/GradientExtension.java src/Scale.java
\warning: [options] bootstrap class path not set in conjunction with -source 1.5
src/GradientExtension.java:3: error: package org.nlogo.api does not exist
import org.nlogo.api.DefaultClassManager;
                    ^
src/GradientExtension.java:4: error: package org.nlogo.api does not exist
import org.nlogo.api.PrimitiveManager;
                    ^
src/GradientExtension.java:6: error: cannot find symbol
public class GradientExtension extends DefaultClassManager {
                                       ^
  symbol: class DefaultClassManager
src/GradientExtension.java:7: error: cannot find symbol
    public void load(PrimitiveManager primitiveManager) {
                     ^
  symbol:   class PrimitiveManager
  location: class GradientExtension
src/Scale.java:5: error: package org.nlogo.api does not exist
import org.nlogo.api.Argument ;
                    ^
src/Scale.java:6: error: package org.nlogo.api does not exist
import org.nlogo.api.Context ;
                    ^
src/Scale.java:7: error: package org.nlogo.api does not exist
import org.nlogo.api.DefaultReporter;
                    ^
src/Scale.java:8: error: package org.nlogo.api does not exist
import org.nlogo.api.ExtensionException ;
                    ^
src/Scale.java:9: error: package org.nlogo.api does not exist
import org.nlogo.api.LogoException ;
                    ^
src/Scale.java:10: error: package org.nlogo.api does not exist
import org.nlogo.api.LogoList;
                    ^
src/Scale.java:11: error: package org.nlogo.api does not exist
import org.nlogo.api.LogoListBuilder;
                    ^
src/Scale.java:12: error: package org.nlogo.api does not exist
import org.nlogo.api.Syntax ;
                    ^
src/Scale.java:14: error: cannot find symbol
public class Scale extends DefaultReporter
                           ^
  symbol: class DefaultReporter
src/Scale.java:22: error: cannot find symbol
    private static LogoList colorLogoListCache = null ;
                   ^
  symbol:   class LogoList
  location: class Scale
src/Scale.java:25: error: cannot find symbol
    public Syntax getSyntax()
           ^
  symbol:   class Syntax
  location: class Scale
src/Scale.java:38: error: cannot find symbol
    public Object report( Argument args[] , Context context )
                          ^
  symbol:   class Argument
  location: class Scale
src/Scale.java:38: error: cannot find symbol
    public Object report( Argument args[] , Context context )
                                            ^
  symbol:   class Context
  location: class Scale
src/Scale.java:39: error: cannot find symbol
            throws ExtensionException
                   ^
  symbol:   class ExtensionException
  location: class Scale
src/Scale.java:170: error: cannot find symbol
    throws ExtensionException
           ^
  symbol:   class ExtensionException
  location: class Scale
src/Scale.java:178: error: cannot find symbol
    void validRGBList( LogoList rgb )
                       ^
  symbol:   class LogoList
  location: class Scale
src/Scale.java:179: error: cannot find symbol
    throws ExtensionException
           ^
  symbol:   class ExtensionException
  location: class Scale
src/Scale.java:29: error: cannot find symbol
            Syntax.ListType() ,   // n list with lists of 3 numbers [[r g b] [r g b] ...]
            ^
  symbol:   variable Syntax
  location: class Scale
src/Scale.java:30: error: cannot find symbol
            Syntax.NumberType() , // number with the value to scale
            ^
  symbol:   variable Syntax
  location: class Scale
src/Scale.java:31: error: cannot find symbol
            Syntax.NumberType() , // number with range1
            ^
  symbol:   variable Syntax
  location: class Scale
src/Scale.java:32: error: cannot find symbol
            Syntax.NumberType()   // number with range2
            ^
  symbol:   variable Syntax
  location: class Scale
src/Scale.java:34: error: cannot find symbol
        int ret = Syntax.ListType() ; // list with 3 numbers [r g b]
                  ^
  symbol:   variable Syntax
  location: class Scale
src/Scale.java:35: error: cannot find symbol
        return Syntax.reporterSyntax( right , ret ) ;
               ^
  symbol:   variable Syntax
  location: class Scale
src/Scale.java:43: error: cannot find symbol
        LogoList colorLogoList = null ;
        ^
  symbol:   class LogoList
  location: class Scale
src/Scale.java:57: error: cannot find symbol
        catch( LogoException e )
               ^
  symbol:   class LogoException
  location: class Scale
src/Scale.java:59: error: cannot find symbol
            throw new ExtensionException( e.getMessage() ) ;
                      ^
  symbol:   class ExtensionException
  location: class Scale
src/Scale.java:64: error: cannot find symbol
            LogoList RGBList = (LogoList) obj;
            ^
  symbol:   class LogoList
  location: class Scale
src/Scale.java:64: error: cannot find symbol
            LogoList RGBList = (LogoList) obj;
                                ^
  symbol:   class LogoList
  location: class Scale
src/Scale.java:126: error: cannot find symbol
                LogoList RGBList = (LogoList) obj;
                ^
  symbol:   class LogoList
  location: class Scale
src/Scale.java:126: error: cannot find symbol
                LogoList RGBList = (LogoList) obj;
                                    ^
  symbol:   class LogoList
  location: class Scale
src/Scale.java:152: error: cannot find symbol
        LogoListBuilder gradientList = new LogoListBuilder() ;
        ^
  symbol:   class LogoListBuilder
  location: class Scale
src/Scale.java:152: error: cannot find symbol
        LogoListBuilder gradientList = new LogoListBuilder() ;
                                           ^
  symbol:   class LogoListBuilder
  location: class Scale
src/Scale.java:161: error: cannot find symbol
            throw new ExtensionException(
                      ^
  symbol:   class ExtensionException
  location: class Scale
src/Scale.java:174: error: cannot find symbol
            throw new ExtensionException( "RGB values must be 0-255" ) ;
                      ^
  symbol:   class ExtensionException
  location: class Scale
src/Scale.java:192: error: package org.nlogo.util does not exist
                org.nlogo.util.Exceptions.ignore( e ) ;
                              ^
src/Scale.java:197: error: cannot find symbol
            throw new ExtensionException( "An rgb list must contain 3 numbers 0-255" +
                      ^
  symbol:   class ExtensionException
  location: class Scale
40 errors
1 warning
make: **\* [gradient.jar] Error 1

**Comment by SethTisue** [comment]
try:

```
NETLOGO=/Applications/NetLogo\\\ 5.2 make
```

as instructed in README.md ("Use the NETLOGO environment variable to tell the Makefile which NetLogo.jar to compile against...").

**Comment by orcutt989** [comment]
@SethTisue Meant to say thanks and that fixed it. Please close. Will read instructions better next time :0)
